apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-cm-env
  namespace: dev
data:
  APP_ENV: dev
  APP_NAME: mi-app
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-cm-env
  namespace: dev
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "env && sleep 3600"]

    envFrom:
      - configMapRef:
          name: dev-cm-env