apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs
spec:
  resources:
    requests:
      storage: 300Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-app
spec:
  selector:
    matchLabels:
      app: logs-app
  template:
    metadata:
      labels:
        app: logs-app
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - while true; do date >> /logs/output.log; sleep 5; done
        volumeMounts:
          - mountPath: /logs
            name: log-vol
      volumes:
        - name: log-vol
          persistentVolumeClaim:
            claimName: pvc-logs
