apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/nginx
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
  storageClassName: manual
  volumeName: pv-nginx
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: myvolume
        ports:
        - containerPort: 80
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: pvc-nginx
