apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        volumeMounts:
        - name: mi-volumen
          mountPath: /usr/share/nginx/html
        - name: log-volume
          mountPath: /var/log/nginx

      volumes:
      - name: mi-volumen
        persistentVolumeClaim:
          claimName: mi-pvc
      - name: log-volume
        persistentVolumeClaim:
          claimName: log-pvc