apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  label:
    tipo: local
spec:
  capacity:
    storage: 1Gi # capacida variable
  volumeMode: Filesystem # raw disk (Filesystem - Block)
  accessModes:
    - ReadWriteOnce # RWO (ReadWriteOnce) - RWX (ReadWriteMany) - ROX (ReadOnlyMany)
  persistentVolumeReclaimPolicy: Retain  ## tengo Retain - Delete
  storageClassName: manual
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
  hostPath:
    path: /mnt/info
