apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  labels:
    app: myapp
spec:
  type: NodePort  ## sirver para exponer el pod fuera del cluster usando el puerto del Nodo (http://IP_NODE:PUERTO_NODEPORT)

  selector:
    app: myapp
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  ## Puerto del Nodo (30000-32767)