apiVersion: batch/v1
kind: CronJob
metadata:
  name: allow-logs
spec:
  schedule: "* * * * *" # Ejecutar cada minut
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: logger
            image: busybox
            command: ["sh", "-c", "echo Inicio && sleep 70 && echo Fin"]
          restartPolicy: Never