apiVersion: v1
kind: Pod
metadata:
  name: pod-completo
  labels:
    app: mi-app
  annotations:
    description: "Pod de ejemplo con los atributos completos"
spec:
  restartPolicy: Always # OnFailure, Never, Always(default)
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo Iniciando... && sleep 5']
  containers:
    - name: app
      image: nginx:alpine
      ports:
        - containerPort: 80
      env:
        - name: ENV
          value: "development"
      resources:
        limits:           # maximo permitido
          memory: "128Mi"
          cpu: "500m"
        requests:       # minimo requerido
          memory: "64Mi"
          cpu: "250m"
      # volumeMounts:
      #   - name: shared-data
      #     mountPath: /usr/share/nginx/html
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
  # volumes:
  #   - name: shared-data
  #     emptyDir: {}