apiVersion: v1
kind: Pod
metadata:
  name: proxy-app
  labels:
    app.kubernetes.io/name: proxy-app
spec:
  containers:
    - name: app-proxy
      image: hashicorp/http-echo
      args:
        - "-text=Hola desde app"
      ports:
        - containerPort: 5678
    - name: proxy
      image: nginx
      ports:
        - containerPort: 80