apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-app
  labels:
    app.kubernetes.io/name: multicontainer-app
spec:
  initContainers:
    - name: init-myservice
      image: busybox
      command: ['sh', '-c', 'echo inicializando.... && sleep 5']

  containers:
    - name: application-container
      image: nginx:alpine
      ports:
        - containerPort: 80