apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-env
data:
  APP_ENV: dev
  APP_NAME: mi-app
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-env
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "env && sleep 3600"]

    envFrom:
      - configMapRef:
          name: cm-env