apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-file
spec:
  containers:
  - name: app-cm
    image: busybox
    command: ["sh", "-c", "cat /secret/db.txt && sleep 3600"]

    volumeMounts:
      - name: secret-vol
        mountPath: /secret
  volumes:
    - name: secret-vol
      secret:
        secretName: secret-file